controller:
  kind: DaemonSet
  
  reportNodeInternalIp: true

  hostPort:
    enabled: true
    ports:
      http: 80
      https: 443

  service:
    type: NodePort

  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/actuator/prometheus"