replicas:
  _default: 1
  dev: 3

selector : dev

name:
  app: notification-helm

service:
  nameApp: notification-helm-service
  portName: port-demo
  type: NodePort
  port: 80
  targetPort: 8002

image:
  repository: bobah165/notification
  tag: v1

ingress:
  enabled: false
  name: "notification-helm-ingress"
  className: nginx
  host: "arch.homework"
  pathType: Prefix
  path:
    person: /api/notification/currentNotification

db:
  url: jdbc:postgresql://my-db-postgresql:5432/postgres


app:
  db:
    password:
      _default: MTIzNDU2
    username:
      _default: cG9zdGdyZXM=

